#!/usr/bin/env python3
"""In-voice one-line descriptions keyed by chapter order then quest title (side chapters, plus Strand-chapter lines not covered by LORE).

Written 2026-09-06 to replace the two-word stubs. generate_quests.py applies these in item_quest().
"""

SIDE_LORE = {
    1: {
        'Ladder Down': 'Climb into the depths without a rope. Cheap enough to leave in every shaft.',
        'String Cache': 'Spider silk saved for later meshes. Every strand gets used eventually.',
        'Oak Leaves': 'Trim them now, compost them later. Nothing on a pad goes to waste.',
        'Wooden Axe': 'Fells logs quicker than bare hands. The first real tool a Skybound owns.',
        'Wooden Shovel': 'Turns dirt and gravel into cleared ground. Slow, but it works.',
        'Wooden Sword': 'Barely stops a zombie, but it stops one. Better than swinging a fist.',
        'Bowl': 'Holds soup, stew, and not much else. Simple crockery for a simple pad.',
        'Oak Door': 'Keeps the wind and the mobs on the correct side of the wall.',
        'Oak Fence': 'Marks an edge without blocking the view. Handy where the drop is real.',
        'Oak Stairs': 'Turns a sheer wall into something you can actually climb.',
        'Oak Slab': 'Half a block, twice the flooring options. Useful in tight spaces.',
        'Oak Pressure Plate': 'Trips a signal when something steps on it. Doors open themselves.',
        'Campfire': 'Cooks food slowly and keeps the smoke visible for miles.',
        'Lantern': 'Hangs light wherever a torch would look wrong. Warmer glow, same job.',
        'Soul Lantern': 'Burns pale blue and keeps most things from spawning nearby.',
        'Scaffolding': 'Climbs with you and vanishes when pulled. Building high stops being scary.',
        'White Wool': 'Soft, flammable, and easy to dye. Every pad needs a bed eventually.',
        'White Carpet': "A thin layer of wool for floors that don't need a whole block.",
        'Flowering Azalea': 'Brings a little green and pink to a pad made of grit.',
        'Moss Block': 'Spreads slowly and softens the look of raw stone platforms.',
        'Glow Lichen': 'Clings to walls and lights them without a single torch.',
        'Copper Block': 'Nine ingots pressed together. Weathers green if you leave it outside.',
        'Raw Iron Block': 'Nine chunks of raw iron stacked tight, waiting on a furnace.',
        'Coal Block': 'Burns far longer than loose coal. Feed the furnace and walk away.',
        'Hay Block': 'Feeds animals and slows a fall. Farmers keep it close for both.',
        'Dried Kelp Block': 'Nine kelp pressed into fuel. Smelts more than it looks like it should.',
        'Book': 'Paper and leather, waiting to become something with a recipe attached.',
    },
    2: {
        'Copper Ore Chunk': 'Sieved from gravel bit by bit. The mesh finds copper before your eyes do.',
        'Iron Hammer': 'Crushes ore into gravel and grit, the noisy trick behind the sieve.',
        'Gunpowder': 'Made from grit and dust, not looted from a creeper. Handle it carefully.',
        'Lapis': 'Feeds the enchanting table. Blue dust that makes gear listen better.',
        'Andesite': 'A common stone blend, useful mostly for building and for mixing recipes later.',
        'Diorite': 'Speckled stone, decorative more than structural. Grit-singers called it the loud one.',
        'Granite': 'Dense and pink-flecked, good for a floor that wants to stand out.',
        'Netherrack': 'Porous rock from the other place. Burns forever once it catches.',
        'Soul Sand': 'Slows every step that crosses it and feeds soul fire a colder blue.',
        'Glowstone Dust': 'Ground from Nether glowstone, useful for brewing and for softer light sources.',
        'Crook': 'Strips leaves off a tree without swinging an axe at the trunk.',
        'String': 'Pulled from the sieve in growing piles. Never quite enough for every mesh.',
        'Bone': "Ground down for meal, or kept whole to breed the pack's next wolf.",
        'Spider Eye': 'Bitter and faintly toxic. Brewers use it, nobody eats it plain.',
    },
    3: {
        'Cabbage': 'Grows in tidy heads, better cooked into something than eaten raw.',
        'Tomato': 'Climbs its own trellis and ripens red. Sauce starts here.',
        'Stone Seeds': 'Grown, not mined. Harvest essence instead of swinging a pickaxe.',
        'Copper Seeds': 'A crop that yields copper essence instead of copper ore.',
        'Gold Seeds': 'Gilded leaves that grow gold essence right on the pad.',
        'Coal Seeds': 'Turns a farm plot into a fuel source, no mining required.',
        'Tertium': 'A deeper grade of crop essence, stronger than the seeds you started with.',
        'Carrot': 'Plant a row, feed a horse, or just eat it raw.',
        'Beetroot': 'Grows fast and dyes red. Soup, stew, or straight from the ground.',
        'Cactus': 'Grows without water and hurts anything that leans on it.',
        'Bamboo': 'Shoots up fast and burns hot. Handy fuel for a pad short on trees.',
        'Cocoa': 'Grown on jungle logs, ground into the brown that flavors everything sweet.',
        'Apple': 'Falls from oak leaves on its own time. Free food, eventually.',
        'Mushroom Stew': "One bowl, no crafting table. The lazy farmer's dinner.",
        'Honey Bottle': 'A taste of the hive before the deeper work with bees begins.',
        'Glow Berries': 'Grow on cave vines and light the tunnel while you eat them.',
        'Nether Wart': 'The base of every potion worth bottling. Grows only on soul sand.',
    },
    4: {
        'Rod Blueprint': 'The template a modular tool starts from before you add its parts.',
        'Diamond Tip': "Sharpens a blade's edge past what iron alone can manage.",
        'Iron Leggings': 'Covers the legs first. Most damage comes from below anyway.',
        'Iron Boots': 'Steadies your footing on ledges where a slip means the void.',
        'Hoe Blueprint': 'The starting template for a modular hoe, built part by part.',
        'Sickle Blueprint': 'Clears a wide swath of crops in one swing instead of one plant.',
        'Paxel Blueprint': 'One tool that mines, chops, and digs. No more swapping in your hand.',
        'Hammer Blueprint': 'Breaks a three by three block of stone in a single hit.',
        'Excavator Blueprint': 'Clears wide holes in dirt and sand faster than any shovel.',
        'Knife Blueprint': 'Small, fast, and precise. Built for close work, not for war.',
        'Gold Armor Bits': 'Soft plating, easily enchanted, worth more for its magic than its defense.',
        'Crossbow': 'Loads slow, hits hard, and holds its charge until you need it.',
    },
    5: {
        'Thermo Generator': 'Burns a heat difference into power. Feed it hot on one side, cold on the other.',
        'Wrench': 'Rotates machines in place instead of breaking and replacing them.',
        'Blast Furnace': 'Smelts ore twice as fast as a regular furnace, ore only.',
        'Smoker': 'Cooks meat twice as fast as a campfire, food only.',
        'Coal Block': 'Nine coal pressed dense. One block outlasts a whole stack of lumps.',
        'Dropper': 'Nudges one item at a time into whatever sits in front of it.',
        'Piston': 'Pushes a block forward on a signal, then waits for the next one.',
        'Sticky Piston': 'Pushes a block out and pulls it back when the signal drops.',
        'Target': 'Registers a hit with signal strength based on how close to center.',
        'Lightning Rod': 'Draws a strike away from your roof and grounds the charge.',
        'Redstone Lamp': 'Lights up on a signal and goes dark the moment it stops.',
        'Daylight Detector': 'Reads the sky and sends a signal that rises and falls with the sun.',
        'Lever': 'Flips a signal on or off by hand. The oldest switch there is.',
        'Pressure Plate': 'Sends a signal when something heavier than air stands on it.',
        'Tripwire Hook': 'Strung with string across a path, it catches anything that crosses.',
        'Note Block': 'Plays one note per block type beneath it. Drumhearts hear a song in a row of them.',
        'Minecart': 'Rolls along track under gravity or a push. No rails, no ride.',
        'Detector Rail': 'Reads a passing cart and fires a signal as it rolls over.',
        'Pipez Wrench': "Sets a pipe's filter and direction without breaking it off the wall.",
    },
    6: {
        'Hand Crank': 'Turns rotation by hand when nothing else is spinning yet.',
        'Depot': 'A flat surface that holds an item still for the belt or press.',
        'Chute': 'Drops items straight down between machines, no belt required.',
        'Mechanical Saw': 'Cuts logs to planks or trees to lumber, given enough rotation.',
        'Portable Storage Interface': "Loads or empties a stopped train's cargo without you lifting a single chest.",
        'Item Vault': 'Stacks nine chests worth of storage into one large block.',
        'Fluid Tank': 'Holds liquid in bulk and links with its neighbors to hold more.',
        'Copper Casing': "Marks the fluid-handling side of a build, andesite's fancier cousin.",
        'Brass Casing': "Covers the precise machines, the ones rotation alone can't satisfy.",
        'Whisk': 'Mixes ingredients in a basin when spun fast enough.',
        'Propeller': "Spins on a shaft and pushes air, or a boat, depending where it's mounted.",
        'White Sail': 'Catches wind on a windmill and dyes easily if you want a pattern.',
        'Windmill Bearing': 'Turns a ring of sails into rotation pulled straight from the sky.',
        'Mechanical Bearing': 'Spins an entire structure around a fixed point, walls and all.',
        'Cart Assembler': 'Turns a stationary build into one that rides the rails.',
        'Minecart Coupling': 'Links two carts so they travel as a single train.',
        'Track': 'Lays the path a cart or contraption travels along.',
        'Display Link': 'Shows a number from elsewhere on a block you can actually see.',
        'Potato Cannon': 'Fires a potato hard enough to knock something back. Mostly for laughs.',
        'Extendo Grip': 'Reaches and breaks blocks from further away than your arm allows.',
    },
    7: {
        'Honey Bottle': 'Sweet, sticky, and worth more to a furnace than to your stomach.',
        'Honey Treat': 'A snack that calms an agitated bee before you reach into the hive.',
        'Expansion Box': 'Gives a hive more room before it swarms looking for a new one.',
        'Catcher': 'Nets a bee out of the air without a single sting.',
        'Diamond Seeds': 'One of the deeper essence crops, grown far past the basics.',
        'Redstone Seeds': 'A farm plot that yields dust instead of digging for it.',
        'Lapis Seeds': 'Grows the blue essence enchanting tables are always hungry for.',
        'Nether Quartz Seeds': 'Quartz grown on leaves instead of dug from Nether caves.',
        'Glowstone Seeds': 'A softer way to farm light than mining the Nether ceiling.',
        'Obsidian Seeds': 'Hardened leaves that yield obsidian essence without a lava bucket in sight.',
        'Supremium': "The last essence tier. Whatever you're building, this is the good version.",
        'Honey Generator': 'Burns honey for power. A hive doing double duty.',
        'Jar': 'Holds one bee on display, wings and all, without a hive attached.',
        'Campfire': 'Calms a hive full of bees before you go digging for honeycomb.',
        'Flowering Azalea': 'Feeds bees and blooms twice a year, evergreen the rest of the time.',
        'Sunflower': 'Tall, yellow, and always facing the sun. Bees find it easily.',
        'Lilac': 'Two blocks of purple bloom that bees will cross a pad to reach.',
        'Rose Bush': 'A tall flower bees favor, and one more color for the garden.',
        'Peony': 'Pink and full, planted wherever a hive needs more forage nearby.',
        'Orange Tulip': "A short, single flower, but bees don't care about height.",
    },
    8: {
        'Bookshelf': 'Surrounds an enchanting table to unlock its strongest enchantments.',
        'Golden Apple': 'Heals deeply and grants a shine that fades after a minute.',
        'Brewing Stand': 'Turns water bottles into something with an actual effect.',
        'Blaze Rod': "Fuels the brewing stand and proves you've already faced the Nether.",
        'Fermented Eye': "Twists a potion's effect into something worse, on purpose.",
        'Source Gem': 'Stores Source, the fuel spells burn through.',
        'Archwood': 'Grown, not found. Wood for casting tools and spell pedestals.',
        'Mage Bloom': 'An arcane crop, grown for its cloth as much as its magic.',
        'Arcane Pedestal': 'Displays a reagent and feeds it into whatever ritual needs it.',
        'Source Jar': 'Stores extra Source so a spell never runs dry mid-cast.',
        'Spirit Fire': "A cold flame used in rituals that regular fire won't finish.",
        'Nature Altar': 'The heart of aura-based crafting, tuned to the land around it.',
        'Gold Fiber': 'A plant infused by high aura, spun into something rarer.',
        'Gold Leaf': 'Aura-touched material, more valuable than it looks lying on the ground.',
        'Infused Iron': "Iron that's soaked up ambient aura until it's worth more than the ore.",
        'Eye': 'Lets you see the aura level of the land around you.',
        'Token Joy': "Raises the aura of the area it's placed in.",
        'Warp Scroll': 'Marks a spot to return to with a word, not a walk.',
        'Magebloom Crop': 'Plant it, tend it, and harvest cloth soaked in low magic.',
        'Blank Glyph': 'The empty page a spell gets written onto.',
        "Iron's Spell Book": 'Casts combat spells without ever touching a wand.',
        'Arcane Essence': 'The fuel spellcasters burn through, spell after spell.',
        'Ink Common': 'Inscribes a spell onto a book, one tier at a time.',
    },
    9: {
        'Certus Dust': 'Ground quartz, the base material the digital loom is built from.',
        'Sky Stone': 'The shell block for every network machine, quarried from certus deposits.',
        'Fluix Dust': 'A blend of quartz, redstone, and glass, ground fine for network crafting.',
        'Inscriber Silicon Press': 'Stamps a silicon plate the way a loom presses cloth.',
        'Logic Press': 'Stamps the die for a logic processor, one press at a time.',
        'Calculation Press': 'Stamps the die for a calculation processor.',
        'Calculation Processor': 'A component in autocrafting patterns, made from silicon and certus quartz.',
        'Engineering Processor': "A denser processor, needed for the network's more demanding parts.",
        'ME Drive': 'Houses the cells that hold everything the network remembers.',
        'Item Cell Housing': 'The shell a storage cell is built inside.',
        'Crafting Terminal': 'Lets you craft directly from whatever the network already holds.',
        'Fluix Cable': "Carries the network's channels from one machine to the next.",
        'Export Bus': 'Pushes items out of the network into a chest or machine.',
        'Storage Bus': 'Reads an outside inventory into the network as if it were a cell.',
        'Crafting Unit': "Adds bulk crafting capacity to the network's autocrafting.",
        'Crafting Co-Processing Unit': 'Speeds up how many crafting jobs run at once.',
        '1k Crafting Storage': 'Holds patterns for the network to draw on while it crafts.',
        'Pattern Provider': 'Feeds patterns to machines the way a loom feeds thread to the shuttle.',
        'Blank Pattern': 'An empty pattern, waiting to be encoded with a recipe.',
        '4k Item Cell': 'A storage cell with more room than the last size.',
        '16k Item Cell': 'Holds far more than any chest, the densest cell before the drive fills up.',
        'Fluid Cell Housing': 'The shell a fluid storage cell is built inside.',
        '1k Fluid Cell': 'A digital tank, storing liquid the network can pull from anywhere.',
        'Formation Plane': 'Places blocks from the network the way a hand would, without one.',
        'Annihilation Plane': 'Breaks blocks in front of it and feeds them into the network.',
        'Interface': 'Connects the network to the world, trading items across the edge.',
        'Quantum Ring': "Links two networks across distance the ordinary cable can't reach.",
        'Quantum Link': 'The paired half of a quantum ring, tying two networks together.',
        'Wireless Terminal': 'Reaches the network from anywhere in range, no cable underfoot.',
        'Memory Card': "Copies one machine's settings onto another without retyping them.",
        'Charger': "Charges certus quartz until it's ready for finer crafting.",
        'Crystal Growth Accelerator': 'Speeds a growing crystal bud toward a full-sized cluster.',
    },
    10: {
        'Bone Crook': 'Sifts faster than the wooden crook, and lasts far longer.',
        'String Mesh': 'The plainest mesh. Everything you sieve starts by passing through this.',
        'Flint Mesh': 'Catches finer shards than string. Fewer scraps slip through the weave.',
        'Iron Mesh': 'Iron threads catch heavier grit and pull rarer scraps from the pile.',
        'Golden Mesh': 'Gold tier mesh. Odds shift toward the ores that matter.',
        'Diamond Mesh': 'Sieve gravel with this and diamonds turn up far more often.',
        'Netherite Mesh': 'The finest mesh made. Nothing sieves better than netherite thread.',
        'Porcelain Clay': 'Clay refined smooth, ready to fire into a crucible that holds real heat.',
        'Porcelain Crucible': 'Holds molten heat without cracking. Smelt what the sieve turned up.',
        'Watering Can Wood': 'Splashes water across crops without trampling the rows.',
        'Watering Can Iron': 'Wider splash and a deeper tank. Water more of the pad per trip.',
        'Silkworm': 'Set loose on leaves, it spins silk while it feeds.',
        'Witch Water Bucket': 'Strange water that nudges saplings and seeds toward stranger crops.',
        'Mycelium Spores': 'Scatter these and mycelium creeps outward, block by patient block.',
        'Grass Seeds': 'Toss on dirt and grass spreads without waiting on the rain.',
        'Stone Pebble': "Cobblestone's replacement grit. Feed it back to the hammer for more.",
        'Compressed Cobble': 'Nine pebbles packed tight into storage stone for a growing pad.',
        'Netherite Hammer': 'Breaks cobble into pebbles faster than any hammer before it.',
        'Blackstone Pebble': 'Nether stone, crushed fine. Basalt and blackstone both start here.',
        'Deepslate Pebble': 'Deepslate crushed down to grit, ready for the sieve again.',
        'Calcite': 'Pale stone pulled from deep sieving, mostly good for building.',
        'Tuff': 'Grey stone from the depths, plain and easy to shape.',
        'Dripstone': 'Grows slow underground; stack it and let it drip into stalactites again.',
        'Sponge': 'Soaks up standing water fast, handy after a flooded farm.',
    },
    11: {
        'Oak Drawer 1x1': 'One slot, sorted and visible. The simplest way to store bulk items.',
        'Oak Drawer 1x2': 'Two slots side by side for keeping similar items apart.',
        'Oak Drawer 2x2': 'Four slots in one frame. Dense storage for a small footprint.',
        'Compacting Drawer': 'Automatically compacts what it holds into blocks as it fills.',
        'Storage Controller': 'Links every drawer on the pad into one searchable network.',
        'Collector Upgrade': 'Pulls nearby item drops straight into the drawer.',
        'Puller Upgrade': 'Pulls items out of the chest or machine set beside it.',
        'Pusher Upgrade': 'Pushes stored items into whatever inventory sits next to it.',
        'Void Upgrade': 'Deletes anything past capacity so the drawer never jams.',
        'Backpack': 'A portable inventory that frees up hotbar and pocket space.',
        'Iron Backpack': 'More slots than the plain backpack, and a slot to upgrade it.',
        'Gold Backpack': 'Roomier still, with slots left over for useful upgrades.',
        'Diamond Backpack': 'The deepest pockets before enchanting takes the storage further still.',
        'Pickup Upgrade': 'Sucks nearby drops straight into the backpack as you walk.',
        'Crafting Upgrade': 'Lets the backpack craft from whatever it already has stored.',
        'Feeding Upgrade': 'Feeds you automatically from its stores when hunger runs low.',
        'Restock Upgrade': 'Swaps a broken tool for a fresh one from the pack.',
        'Deposit Upgrade': 'Empties the backpack into nearby chests when you get close.',
        'Tank Upgrade': 'Adds a fluid tank inside the backpack for hauling liquids.',
    },
    12: {
        'Steel Ingot': 'The backbone metal behind most machines and casings on this line.',
        'Osmium Ingot': 'The core metal behind most cables, tanks, and early machines.',
        'Refined Obsidian': 'A hard alloy pressed from obsidian dust for tougher gear.',
        'Basic Control Circuit': 'The simplest logic board. Most early machines need a few.',
        'Advanced Control Circuit': 'A sharper logic board for the machines a step up the line.',
        'Elite Control Circuit': "The sharpest logic board, reserved for the line's top machines.",
        'Metallurgic Infuser': 'Infuses metals with carbon, redstone, or diamond dust before smelting.',
        'Enrichment Chamber': 'Doubles most raw ores into two dusts instead of one.',
        'Energized Smelter': 'Smelts ores on power instead of fuel, and a little faster too.',
        'Purification Chamber': 'Purifies enriched ore with oxygen for a third output, sometimes more.',
        'Chemical Injection': 'Injects gas into ore for the richest output the line offers.',
        'Osmium Compressor': 'Compresses osmium dust into ingots faster than a furnace alone.',
        'Basic Bin': 'A single stack slot that holds far more than a chest can.',
        'Basic Fluid Tank': 'Stores a deep pool of one fluid in a single block.',
        'Basic Energy Cube': "Buffers power between machines so surges don't stall the line.",
        'Basic Universal Cable': 'Carries power to machines. The most common cable on the pad.',
        'Basic Mechanical Pipe': 'Moves fluids between tanks and machines along the pad.',
        'Basic Logistical Transporter': 'Moves items automatically between connected inventories.',
        'Configurator': 'Rotates, wrenches, and reconfigures machine faces with one tool.',
        'Free Runners': 'Softens fall damage and buys a second before the void claims you.',
        'Atomic Disassembler': 'One tool that mines, cuts, and fights, sharper with every upgrade.',
        'Steel Casing': 'The structural frame most multiblock machines are built around.',
        'Teleporter': 'Links two points so stepping through skips the walk between.',
        'Digital Miner': 'Mines a wide radius automatically and sorts the output for you.',
    },
    13: {
        'Dielectric Paste': "A sticky base ingredient behind most of the grid's machines.",
        'Energy Cell Basic': 'Stores a deep reserve of power for the machines around it.',
        'Furnator Basic': 'Burns fuel into power more efficiently than a plain furnace.',
        'Magmator Basic': 'Turns lava into steady power for as long as the lava lasts.',
        'Solar Basic': 'Generates power from daylight, more than a single cell manages alone.',
        'Thermo Basic': 'Generates power from the gap between hot and cold nearby blocks.',
        'Reactor Basic': 'Burns solid fuel steadily for a strong, dependable trickle of power.',
        'Energy Cable Basic': 'Moves more power per tick than the starting cable.',
        'Player Transmitter Basic': 'Charges the player directly, no wires or slots required.',
        'Energy Hopper Basic': 'Feeds power into nearby machines the way a hopper feeds items.',
        'Energizing Rod Basic': 'Charges energizing cells faster when placed beside the crystal setup.',
        'Battery Basic': 'A pocket reserve of power to carry between machines by hand.',
        'Niotic Crystal': "The first crystal tier for the energizing rod's cell chamber.",
        'Spirited Crystal': "A stronger crystal tier, further along the energizing chamber's build.",
        'Nitro Crystal': 'The strongest crystal tier the energizing chamber can hold.',
    },
    14: {
        'Mage Fiber': 'Spun from magebloom, and woven into robes and spell gear.',
        'Magebloom': 'A flower that regrows its fiber on the stem after harvest.',
        'Source Gem Block': 'Stores a dense pool of source, the fuel behind every spell.',
        'Apprentice Spell Book': 'Holds more glyphs than the starting book allows.',
        'Archmage Spell Book': 'The largest spell book, room enough for a full arsenal of glyphs.',
        'Spell Turret': 'Casts a bound spell automatically whenever it senses a target.',
        'Timer Spell Turret': 'Casts its bound spell on a steady timer instead of on sight.',
        'Enchanting Apparatus': 'The centerpiece for crafting spell books, wands, and other arcane gear.',
        'Arcane Core': 'Sits inside the enchanting apparatus and drives its recipes.',
        'Relay': 'Carries source between an arcane spot and a linked jar or spell.',
        'Relay Splitter': 'Splits one source line so it feeds several places at once.',
        'Agronomic Sourcelink': 'Converts nearby crop growth into a slow trickle of source.',
        'Volcanic Sourcelink': 'Converts nearby lava heat into a steady trickle of source.',
        'Wixie Charm': 'Summons a wixie that crafts recipes for you while you work elsewhere.',
        'Starbuncle Charm': 'Summons a starbuncle that fetches items from storage on command.',
        'Drygmy Charm': 'Summons a drygmy that slowly generates a chosen resource nearby.',
        'Whirlisprig Charm': 'Summons a whirlisprig that tends and grows crops on its own.',
        'Amethyst Golem Charm': 'Summons a golem that harvests amethyst buds without lifting a pick.',
        'Dominion Wand': 'Picks up and places blocks remotely, wiring machines together at range.',
        'Allow Scroll': 'Marks an item as allowed when set into a filter.',
        'Deny Scroll': 'Marks an item as denied when set into a filter.',
    },
    15: {
        'Hub Key': 'Opens the way back to the Clowder Hall from anywhere on the Strand.',
        'Strand Banner': 'A banner pattern that marks how far your Strand has come.',
        'Map': 'Charts the pads around you as your Clowder spreads outward.',
        'Compass': 'Points back toward the world spawn, useful once pads multiply.',
        'Lodestone': 'Anchors a compass to one exact spot instead of spawn.',
        'Recovery Compass': 'Points toward your last death, so nothing stays lost in the void.',
        'Bell': 'Rings loud enough to gather the whole Clowder to one pad.',
        'Lectern': 'Holds a book open for the whole Clowder to read.',
        'Oak Sign': 'Labels a district so newcomers know which pad is which.',
        'White Banner': "A blank banner ready to take the Clowder's colors.",
        'Firework': 'Set these off when a Strand finally comes back together.',
        'Cake': 'Shared food for celebrating a Strand well and truly rewoven.',
        'Lead': 'Leads a tamed or bought animal back to the pad without chasing.',
    },
    16: {
        'Buy XP Bottles': 'Spends thread on bottled experience, ready to smash for levels.',
        'Buy Gold': 'Trades thread for gold nuggets, no mining required.',
        'Buy Nether Wart': 'Turns thread into nether wart, enough to start a potion farm.',
        'Buy Obsidian': "Spends thread on obsidian, useful before you've found any of your own.",
    },
    17: {
        'Eye': 'Shows where aura pools thick or thin across the land.',
        'Gold Fiber': 'Woven from gold, used to infuse plants with concentrated aura.',
        'Gold Leaf': "A refined material used in the altar's higher tier recipes.",
        'Golden Leaves': 'Leaves that hold a soft golden glow year round.',
        'Wood Stand': 'Holds an offering for the nature altar to consume.',
        'Nature Altar': 'The altar where aura powers stronger crafting recipes.',
        'Infused Iron': 'Iron charged with aura, a step toward the depths powder.',
        'Ancient Bark': 'Bark stripped from ancient trees, useful in aura recipes.',
        'Token Joy': 'Charges an area with joy, boosting nearby crop growth.',
        'Token Fear': 'Charges an area with fear, driving hostile mobs away.',
        'Token Anger': 'Charges an area with anger, provoking nearby mobs to fight.',
        'Token Sorrow': 'Charges an area with sorrow, slowing mobs that wander through.',
        'Aura Troves': 'Stores a reserve of aura for when the land runs thin.',
        'Environmental Eye': 'Reveals aura and spawn conditions over a wider stretch of land.',
        'Crushing Catalyst': 'Uses ambient aura to crush ores dropped nearby, no machine needed.',
        'Conversion Catalyst': 'Converts items dropped nearby using stored aura, no crafting table needed.',
        'Depths Powder': 'A refined powder pulled from aura deep underground.',
        'Farming Stencil': 'Marks a farm layout that draws aura into faster crop growth.',
        'Projectile Generator': 'Generates aura whenever a projectile lands nearby.',
        'Flower Generator': 'Generates aura slowly from flowers blooming nearby.',
        'Oak Generator': 'Generates aura slowly from oak trees growing nearby.',
        'End Flower': 'A flower from the end, oddly at home on a floating pad.',
        'Spawn Lamp': 'Lights an area to keep hostile mobs from spawning there.',
    },
    18: {
        'Cooking Pot': 'Cooks stew-type meals that feed more than one plate at once.',
        'Cutting Board': 'Cuts meat and vegetables into ingredients other recipes call for.',
        'Rope': 'Climbable like a vine, and needed for several kitchen recipes.',
        'Safety Net': 'Catches a long fall and bounces you back up unharmed.',
        'Rich Soil': "Boosts nearby crop growth once it's tilled and planted.",
        'Organic Compost': 'Turns food scraps into compost for enriching soil.',
        'Cabbage Rolls': 'A hearty meal wrapped from cabbage, restores a solid chunk of hunger.',
        'Bacon Sandwich': 'Quick to cook, quick to eat, decent hunger for the effort.',
        'Hamburger': 'A layered meal that restores more hunger than the parts alone.',
        'Chicken Soup': 'A warming bowl that restores hunger and saturation together.',
        'Noodle Soup': "Noodles and broth, filling enough for a full day's work.",
        'Apple Pie': 'A baked dessert worth the wait, restores a generous chunk of hunger.',
        'Sweet Berry Cheesecake': 'Tart and sweet, one of the richer desserts on the pad.',
        'Dumplings': 'Small filled parcels, quick to cook in batches.',
        'Hot Cocoa': 'A warm drink brewed from cocoa beans and milk.',
        'Melon Juice': 'A cool drink pressed from melon, restores a little hunger fast.',
        'Canvas': 'Woven cloth used in several kitchen and decor recipes.',
        'Tatami': 'Soft woven flooring, a change of texture from plain wood.',
    },
    19: {
        'Iron Spell Book': 'The first book that lets you cast spells in a real fight.',
        'Gold Spell Book': 'Holds more spell slots than the iron book before it.',
        'Diamond Spell Book': 'A sturdier book with even more room for spells.',
        'Arcane Essence': 'Fuels spellcasting and sits at the base of most spell recipes.',
        'Uncommon Ink': 'Writes uncommon-tier spells and scrolls into a book.',
        'Rare Ink': 'Writes rare-tier spells and scrolls into a book.',
        'Epic Ink': 'Writes epic-tier spells and scrolls into a book.',
        'Legendary Ink': 'Writes the rarest, strongest spells a book can hold.',
        'Scroll': 'Casts a spell once without needing it learned in a book.',
        'Wandering Magician Helmet': 'Light armor that favors spellcasting over raw defense.',
        'Wandering Magician Chestplate': 'Chest armor built for casting speed rather than damage soaked.',
        'Pyrium Staff': 'A staff that channels fire spells with extra force.',
        'Graybeard Staff': 'A modest staff for a caster just starting out.',
        'Magehunter': 'A blade that punishes spellcasters, cutting through their defenses.',
        'Copper Spell Book': 'The earliest spell book, light on slots but easy to reach.',
        'Netherite Spell Book': 'The strongest spell book, holding the most spell slots of all.',
        'Arcane Ingot': 'Refined metal used across the higher end of spellcasting gear.',
        'Ruined Codex': 'A damaged book that can be pieced back into knowledge.',
    },
    20: {
        'Mirror': 'Redirects sunlight toward a solar tower for a bigger yield.',
        'Photovoltaic Cell 1': 'The first tier of solar cell, weak but cheap to stack.',
        'Photovoltaic Cell 2': 'A stronger solar cell, a step up from the last tier.',
        'Photovoltaic Cell 3': 'Mid tier solar cell, noticeably more output per panel.',
        'Photovoltaic Cell 4': 'A high tier solar cell for a panel built to scale.',
        'Photovoltaic Cell 5': 'Near the top tier, this cell pulls serious power from daylight.',
        'Photovoltaic Cell 6': 'The strongest solar cell made, the ceiling for a single panel.',
        'Capacity Upgrade': 'Lets a solar panel hold a larger reserve of stored power.',
        'Efficiency Upgrade': 'Squeezes more power out of the same sunlight.',
        'Transfer Upgrade': 'Lets a solar panel send power out faster.',
        'Traversal Upgrade': "Lets the panel track the sun's path for steadier output.",
        'Dispersive Upgrade': 'Spreads charge across nearby machines instead of one output line.',
        'Block Charging Upgrade': 'Lets the panel charge chargeable blocks placed against it directly.',
        'Furnace Upgrade': 'Lets the panel smelt items using stored sunlight instead of fuel.',
        'Emerald Glass': 'Colored glass panel for solar builds, mostly decorative shading.',
        'Ender Glass': "A dark, void-toned glass panel for a solar tower's frame.",
        'Blazing Coating': 'A coating that helps the panel handle intense heat.',
        'Blank Upgrade': 'An uncommitted upgrade item, crafted into any upgrade type.',
    },
    21: {
        'Stone Bricks': 'Plain, dependable stone for walls and floors.',
        'Cracked Stone Bricks': 'Weathered stone bricks with a worn, cracked look.',
        'Chiseled Stone Bricks': 'Carved stone bricks for trim and accent lines.',
        'Smooth Stone': 'A flat, even stone finish for floors.',
        'Polished Andesite': 'Grey stone polished to a smooth finish.',
        'Polished Diorite': 'Bright white stone, polished smooth.',
        'Polished Granite': 'Warm pink stone, polished for detailing.',
        'Bricks': 'Fired clay blocks, warm red against grey stone.',
        'Mud Bricks': 'Pale, packed mud shaped into building trim.',
        'Deepslate Bricks': 'Dark stone bricks pulled from the deep.',
        'Deepslate Tiles': 'Smooth dark tiles for a sleeker floor.',
        'Blackstone': 'Dark nether stone, sturdy and plain.',
        'Polished Blackstone': 'Blackstone polished to a glossy dark sheen.',
        'Gilded Blackstone': 'Blackstone flecked with gold, rare and decorative.',
        'Quartz Block': 'Bright white block, a pad decor staple.',
        'Smooth Quartz': 'Quartz smoothed flat for clean trim work.',
        'Purpur Block': 'Purple end stone, an odd accent piece.',
        'Prismarine': 'Sea-born stone with a faint blue shimmer.',
        'Dark Prismarine': 'A darker prismarine, good for deep accents.',
        'Sea Lantern': 'A steady light pulled from the ocean floor.',
        'Shroomlight': 'A warm orange light grown from nether fungus.',
        'Ochre Froglight': 'A soft yellow light with no flame at all.',
        'Pearlescent Froglight': 'A pale, glowing light with a pearled sheen.',
        'Verdant Froglight': 'A cool green light, flameless and safe indoors.',
        'Tinted Glass': 'Glass that blocks light but keeps the view.',
        'White Stained Glass': 'Soft white glass for gentle window light.',
        'Light Blue Stained Glass': 'Pale blue glass, close to open sky.',
        'Cyan Stained Glass': 'Cool teal glass for a calmer room.',
        'Purple Stained Glass': 'Deep purple glass, a nod to the void below.',
        'Candle': 'A small steady flame for mood lighting.',
        'White Candle': 'A pale candle, subtle against light walls.',
        'Oak Boat': 'Keeps you afloat if the pad ever meets water.',
        'Armor Stand': 'Displays a full set of armor on the pad.',
        'Glow Item Frame': 'Holds a displayed item that never goes dark.',
        'Stonecutter': 'Cuts stone into precise shapes without the waste.',
        'Grindstone': 'Repairs tools and strips unwanted enchantments.',
        'Smithing Table': 'Upgrades gear with smithing templates and netherite.',
        'Fletching Table': 'A villager workstation, mostly decorative on the pad.',
        'Blast Furnace Spare': 'Smelts ores twice as fast as a plain furnace.',
        'Smoker Spare': 'Cooks food twice as fast as a plain furnace.',
        'Cauldron': 'Holds a small amount of water, dye, or potion.',
        'Hopper Spare': 'Moves items automatically between containers below and above.',
        'Dispenser Spare': 'Fires or uses whatever item is loaded into it.',
        'Observer Spare': 'Pulses redstone whenever the block in front changes.',
        'Redstone Block': 'A constant, strong redstone signal in block form.',
        'Target Spare': "Sends a signal strength based on how well it's hit.",
        'Jukebox Spare': 'Plays music discs across the pad.',
        'Respawn Anchor': 'Sets your respawn point in the nether, charged with glowstone.',
        'Lodestone Spare': 'Locks a compass to this exact block instead of spawn.',
        'Lightning Rod Spare': 'Draws lightning strikes safely away from the pad.',
        'Ender Chest': 'A personal storage space that follows you everywhere you go.',
        'Shulker Shell': 'Crafts into a shulker box for stackable, safe storage.',
    },
    22: {
        'Netherrack Stock': "The floor and walls of anywhere you're building over lava.",
        'Nether Bricks': 'Fired mudstone braced with quartz. Holds shape near fire.',
        'Red Nether Bricks': 'Nether wart baked into brick. Warmer color, same strength.',
        'Basalt': 'Cooled magma column, cut into blocks for a foothold.',
        'Polished Basalt': 'Basalt sanded smooth. Reads as stone, not scaffolding.',
        'Smooth Basalt': 'Basalt without the ridges. Good for flat floors and trim.',
        'Blackstone Stock': "The Nether's cobblestone. Craft it toward tools and bricks.",
        'Magma Block': 'Warms nearby water to a boil and hurts bare feet.',
        'Soul Soil': 'Lets soul fire and soul torches burn instead of ordinary flame.',
        'Glowstone': 'Crushes into four dust, or lights a room without smoke.',
        'Shroomlight Stock': 'A fungus that glows on its own. No wiring needed.',
        'Nether Wart Block': 'Nine wart bundled into a block. Mostly decoration and dye.',
        'Warped Wart Block': 'Blue cousin of the crimson block. Same recipe, cooler color.',
        'Crimson Stem': "Wood that isn't wood. Strips and planks like any log.",
        'Warped Stem': 'The other fungus trunk. Planks come out blue instead of red.',
        'Twisting Vines': 'Climbs a warped forest and marks a foothold in the haze.',
        'Crying Obsidian': 'Weeps purple light and anchors a respawn point in the Nether.',
        'Ancient Debris': 'Buried below the ordinary ores. Smelt it toward netherite.',
        'Netherite Scrap': 'Four scraps and four gold ingots make one netherite ingot.',
        'Netherite Ingot': 'The hardest metal a Skybound hand will ever hold.',
        'Blaze Rod Stock': 'Fuels brewing stands and blast furnaces both. Keep a stack spare.',
        'Ghast Tear': 'The regeneration potion needs one, plus patience near a ghast.',
        'Magma Cream': 'Brews into fire resistance, or crafts back into a magma block.',
        'Wither Skeleton Skull': 'Three summon a wither. One looks fine on a shelf too.',
        'Gold Nugget Pile': 'Piglins trade for gold. Nuggets work as well as ingots.',
        'Nether Gold Ore': "Smelts to gold and mines faster than the ore it's named for.",
        'Quartz': 'Bright white stone that builds and channels comparator signals both.',
        'Fire Charge': 'Thrown, it starts a fire. Loaded in a dispenser, it does too.',
    },
    23: {
        'End Stone': 'Pale stone from the far side. Heavy, plain, and endless.',
        'End Stone Bricks': 'End stone cut square, for cleaner lines on an end pad.',
        'Purpur Block Stock': 'Grown from chorus fruit, then baked into building stone.',
        'Purpur Pillar': 'Purpur with a column pattern, oriented however you place it.',
        'End Rod': 'A cold light that never flickers and doubles as a rail post.',
        'Chorus Fruit': 'Eat it and you teleport a short, unpredictable hop.',
        'Popped Chorus': 'Chorus fruit cooked. Crafts into purpur and dyes without teleporting you.',
        'Ender Pearl Stock': 'Throw it and you arrive where it lands, minus some health.',
        'Dragon Egg Show': "The dragon's only trophy. It never sits still when clicked.",
        'Shulker Box Show': 'A portable chest that keeps its contents when you break it.',
        'Ender Chest Show': 'Every ender chest on every pad shares one hidden storage.',
        'Chorus Flower': 'Plant it on end stone and it grows chorus fruit upward.',
        'End Portal Frame': 'Twelve of these, filled with eyes, open the way to the end.',
        'Black Concrete': 'Concrete powder set solid. Void-dark and permanent once it cures.',
        'Purple Concrete': 'A loud accent color for a quiet, pale biome.',
        'Obsidian Stock': 'Cooled lava on contact with water. Blast resistant, slow to mine.',
        'Crying Obsidian Stock': 'Glows faintly and, charged, launches you from a respawn anchor.',
        'Respawn Anchor Show': 'Charge it with glowstone to set a Nether respawn point.',
        'Totem Show': 'Held in the off-hand, it cancels one otherwise fatal hit.',
        'Nether Star Show': "The wither's only drop. A beacon needs one to light up.",
        'Beacon Show': 'Powered by a pyramid of mineral blocks, it grants standing buffs.',
        'Conduit Show': 'Surrounded by prismarine, it grants water breathing and haste underwater.',
        'Heart of the Sea': 'Combine it with nautilus shells to build a conduit.',
        'Nautilus Shell': "Eight ring a conduit and one crafts into the sea's compass.",
        'Trident Show': "A drowned's rare drop. Throw it, or channel lightning in a storm.",
    },
    24: {
        'Inferium Stock': 'Base essence. Feeds growth accelerators and reprocessors alike.',
        'Prosperity Base': 'An unfinished seed. Needs essence before it grows anything.',
        'Infusion Crystal': 'Consumed once, it upgrades essence to the next tier.',
        'Prudentium Stock': 'Second-tier essence, refined from stacks of inferium.',
        'Tertium Stock': 'Third-tier essence, a rung above prudentium.',
        'Imperium Stock': 'Fourth-tier essence, close to the top of the chain.',
        'Supremium Stock': 'Fifth-tier essence, nearly as refined as it gets.',
        'Awakened Essence': 'The refined peak. Needed for the strongest gear and seeds.',
        'Awakening Altar': 'The centerpiece for awakening essence into its final form.',
        'Awakening Pedestal': 'Ring the altar with these to complete the awakening.',
        'Master Crystal': 'An infusion crystal that never runs out of charges.',
        'Essence Vessel': 'Stores essence in bulk so machines never run dry.',
        'Machine Frame': 'The base component for every essence-powered machine.',
        'Harvester': 'Watches nearby crops and breaks them the moment they ripen.',
        'Seed Reprocessor': 'Turns spare seeds back into essence instead of clutter.',
        'Inferium Accel': 'Speeds up nearby crops using inferium essence.',
        'Prudentium Accel': 'A stronger accelerator, one tier past inferium.',
        'Tertium Accel': 'Mid-tier acceleration for a busier field.',
        'Imperium Accel': 'Near the top of the growth-speed range.',
        'Supremium Accel': 'The fastest accelerator essence can build.',
        'Watering Can': 'A basic splash of hydration for thirsty crops.',
        'Inferium Can': 'A watering can infused with inferium, wider reach.',
        'Prudentium Can': 'Waters more crops per use than the basic can.',
        'Tertium Can': 'A mid-tier can with a noticeably wider splash.',
        'Imperium Can': 'Waters a broad patch of field in one pass.',
        'Supremium Can': 'The widest splash a watering can can manage.',
        'Fertilized Essence': 'Speeds up growth when tossed onto planted crops.',
        'Soulium Dust': 'Ground from soulium ingots. A component for hostile seeds.',
        'Soulium Ingot': 'Smelted from soulium dust, dark and a little cold.',
        'Soulium Dagger': 'Crafted from soulium. Deals extra damage to hostile mobs.',
        'Soulium Seed Base': 'The unfinished seed for farming hostile mobs.',
        'Redstone Seeds': 'Grow redstone dust instead of mining for it.',
        'Lapis Seeds': 'A field of blue instead of a cave full of it.',
        'Diamond Seeds': 'Grows diamonds on a stem instead of underground.',
        'Emerald Seeds': 'Farms emeralds without a single villager trade.',
        'Obsidian Seeds': 'Grows obsidian without a bucket of water in sight.',
        'Nether Quartz Seeds': 'Farms quartz without setting foot in the Nether.',
        'Glowstone Seeds': 'Grows light without a trip to the Nether ceiling.',
        'Netherite Seeds': 'The rarest crop. Grows scrap toward the hardest metal.',
        'Amethyst Seeds': 'Farms amethyst shards without a single geode.',
        'Honey Seeds': 'Grows honey bottles without a single sting.',
        'Prismarine Seeds': 'Farms prismarine without an ocean monument nearby.',
        'Basalt Seeds': 'Grows basalt columns without a trip to the Nether.',
        'Nether Seeds': 'A general-purpose crop for Nether resources.',
        'End Seeds': 'A general-purpose crop for end resources.',
        'Sky Stone Seeds': 'Grows sky stone for a network that needs it.',
        'Certus Seeds': 'Farms certus quartz for crystal growth and crafting.',
        'Fluix Seeds': 'Grows fluix crystals for network components.',
        'Silicon Seeds': 'Farms silicon for processors and circuits.',
        'Steel Seeds': 'Grows steel without a single furnace running.',
        'Osmium Seeds': 'Farms osmium for early alloy work.',
        'Tin Seeds': 'Grows tin for bronze and basic alloys.',
        'Aluminum Seeds': 'Farms aluminum for lightweight alloy components.',
        'Uranium Seeds': 'Grows uranium. Handle the ore with some care.',
        'Uraninite Seeds': 'Farms uraninite for reactor fuel down the line.',
        'Experience Seeds': 'Grows bottled experience instead of grinding mobs for it.',
        'Slime Seeds': 'Farms slimeballs without hunting a swamp at night.',
        'Blaze Seeds': 'Grows blaze rods without a trip to a fortress.',
        'Ghast Seeds': 'Farms ghast tears without floating over lava.',
        'Enderman Seeds': 'Grows ender pearls without provoking a single enderman.',
        'Wither Skel Seeds': 'Farms wither skeleton skulls at a much safer distance.',
        'Cow Seeds': 'Grows leather without raising a single cow.',
        'Sheep Seeds': 'Farms wool in every dye color at once.',
        'Chicken Seeds': 'Grows feathers without keeping a coop.',
        'Pig Seeds': 'Farms porkchops without raising a single pig.',
        'Skeleton Seeds': 'Grows bones without a night spent fighting skeletons.',
        'Zombie Seeds': 'Farms rotten flesh, mostly for the compost bin.',
        'Creeper Seeds': 'Grows gunpowder without the risk of an explosion.',
        'Iron Essence': 'Grows on a mystical tree instead of underground.',
        'Gold Essence': 'A gilded leaf that drops gold instead of apples.',
        'Diamond Essence': 'The hardest leaf on the tree, quite literally.',
        'Coal Essence': 'Grows fuel on a tree instead of in a seam.',
        'Copper Essence': 'Grows copper on a tree instead of a vein.',
        'Redstone Essence': 'Grows dust on a tree instead of underground.',
    },
    25: {
        'Advanced Oak Hive': 'A proper hive with more slots than a wild nest.',
        'Expansion Box': 'Bolts onto a hive to add more bee living space.',
        'Jar Oak': 'Traps a bee in glass so you can carry it.',
        'Sturdy Cage': 'Holds a bee safely for transport between pads.',
        'Catcher': 'Scoops bees into jars automatically, no net required.',
        'Feeder': 'Keeps a hive fed so the bees keep working.',
        'Bottler': "Fills bottles from a hive's stored honey.",
        'Centrifuge': 'Spins honeycomb apart into honey, wax, and combs.',
        'Powered Centrifuge': 'A centrifuge that spins on its own once powered.',
        'Heated Centrifuge': 'Spins faster with a heat source feeding it.',
        'Incubator': 'Hatches bee larvae into new bees with useful traits.',
        'Breeding Chamber': 'Pairs two bees and produces offspring with mixed traits.',
        'Gene Indexer': "Reads a bee's traits and records them for breeding.",
        'Honey Generator': 'Burns honey for a slow, steady trickle of power.',
        'Honey Treat': 'A snack that keeps a caged bee calm and healthy.',
        'Honey Bucket': 'A full bucket of honey, ready to pour or burn.',
        'Wax Stock': "Melts down for candles or seals a hive's frame.",
        'Configurable Comb': 'A honeycomb that can be tuned to match any bee.',
        'Gene Sample': "A bee's traits, extracted and ready to bottle.",
        'Gene Bottle': "One bee's genetics, stored for later breeding.",
        'Honeycomb Block': 'Six combs pressed solid, mostly for building with.',
        'Honey Block': 'Slows falls and movement. Sticky underfoot, sweet in a hopper.',
        'Beehive Vanilla': 'A wild hive. Smoke it calm before you take the comb.',
        'Campfire Under': 'Smoke from below keeps bees calm during harvest.',
        'Dandelion Field': 'More flowers nearby means more pollen for the hive.',
        'Azalea Bloom': 'A showier flower that some bees prefer over dandelions.',
        'Chorus Snack': 'An end fruit some bees will happily forage from.',
        'Obsidian Treat': 'An odd favorite for a few of the tougher bees.',
        'Birch Expansion': 'More rooms for the hive, cut from birch this time.',
        'Spruce Expansion': 'Spruce-paneled rooms bolted onto the hive.',
        'Dark Oak Expansion': 'Dark oak paneling, same purpose: more bee rooms.',
        'Acacia Expansion': "Acacia rooms for a hive that's outgrown itself.",
        'Jungle Expansion': 'Jungle wood rooms, just as roomy as the rest.',
        'Cherry Expansion': 'Cherry-paneled rooms, purely a matter of style.',
        'Crimson Expansion': 'Crimson-paneled rooms for a hive gone Nether.',
        'Warped Expansion': 'Warped-paneled rooms, the blue half of the pair.',
        'Bamboo Expansion': 'Bamboo rooms, lighter and just as functional.',
        'Mangrove Expansion': 'Mangrove rooms, the newest wood on the list.',
        'Honey Bottle Stock': 'Honey you can drink straight from the bottle.',
        'Sugar Stock': 'Crafts into treats and cakes for a hungry Clowder.',
        'Glass Bottle Stock': 'Empty and waiting for honey, potions, or experience.',
        'Shears Spare': 'A backup pair for cutting comb without hurting the bees.',
    },
    26: {
        'Item Pipe': 'Carries items between chests, machines, and pads.',
        'Fluid Pipe': 'Carries liquids between tanks and machines without a bucket run.',
        'Energy Pipe': 'Carries power between machines that make it and machines that need it.',
        'Gas Pipe': 'Carries chemicals between machines that handle them.',
        'Pipe Wrench': 'Right-click a pipe to set its direction and filters.',
        'Improved Upgrade': 'Slot into a pipe to move more per tick.',
        'Advanced Upgrade': 'The stronger upgrade, for a line under heavy load.',
        'Filter Tool': 'Sets which items a pipe end will accept or ignore.',
        'Hopper Spare': 'The original mover. Slow, cheap, and always useful.',
        'Dispenser Line': "Fires or places whatever's loaded when it gets a signal.",
        'Comparator': 'Reads how full a container is and outputs a signal.',
        'Redstone Torch': 'An always-on signal source, or an inverter next to a lever.',
        'Target Block': 'Struck by a projectile, it sends out a signal by strength.',
        'Daylight Detector': 'Reads the sky and signals based on light or time.',
        'Lectern': 'Holds a book and signals when a page turns.',
        'Trapped Chest': "Signals while it's open, like a chest with a tripwire.",
        'Create Funnel': 'Loads a belt or pulls items off one, depending on facing.',
        'Brass Funnel': 'A funnel that can filter what it moves.',
        'Chute': 'Drops items straight down between floors.',
        'Smart Chute': 'A chute that can filter and hold back items.',
        'Mek Logistical': 'Sorts and moves items with configurable priority per side.',
        'Mek Pipe': 'Moves fluids with pressure, so it climbs as easily as it drops.',
        'Mek Cable': 'Carries power between machines, with several throughput tiers available.',
        'Mek Tube': 'Moves chemicals and gases through a sealed line.',
        'Adv Transporter': 'A faster line for moving items across a busy pad.',
        'Elite Transporter': "Faster still, for a network that's outgrown the basics.",
        'Ult Transporter': 'The fastest item line available, for a maxed-out pad.',
        'Ult Cable': 'The highest-throughput power line, for heavy machine rooms.',
    },
    27: {
        'Dictionary of Spirits': 'Lists every spirit you can bind and what it needs.',
        'Spirit Fire': 'Burns violet and never spreads. Used to light rituals.',
        'Divination Rod': 'Points toward buried ore or hidden structures nearby.',
        'Brush': "Wipes ritual chalk off the ground when you're done.",
        'Otherworld Sapling': "Grows into a tree that doesn't belong to this world.",
        'Otherworld Log': 'Timber from a stranger tree, used in binding rituals.',
        'Sacrificial Bowl': 'Holds an offering while a binding ritual runs.',
        'Golden Bowl': "A gilded bowl that speeds up the ritual it's used in.",
        'Empty Binding Book': "An unsigned contract, waiting for a spirit's name.",
        'Foliot Book': 'Binds the weakest class of spirit, a good first try.',
        'Djinni Book': 'Binds a mid-strength spirit, stronger work than a foliot.',
        'Afrit Book': 'Binds a fierce spirit. The ritual takes more preparation.',
        'Marid Book': 'Binds the strongest spirit in the dictionary.',
        'Spirit Attuned Gem': 'A focus that helps a ritual hold its shape.',
        'Raw Iesnium': 'Ore from beyond this world, smelted into iesnium.',
        'Iesnium Ingot': 'A metal that only exists on the other side.',
        'Dimensional Mineshaft': 'Sends bound spirit miners into the otherworld to dig.',
        'Foliot Miner': 'The weakest spirit put to work mining underground.',
        'Storage Controller': 'Links spirit storage jars into one searchable network.',
        'Amethyst Focus': 'Draws certain spirits toward a ritual circle.',
        'Gold Ingot Stock': 'Melts down for golden bowls and other ritual gear.',
        'Book Stock': 'Blank pages, ready to become a binding book.',
        'Purple Dye': 'Colors ritual chalk for marking a summoning circle.',
        'White Dye': 'Colors ritual chalk, a plainer mark than purple.',
        'Black Dye': 'Colors ritual chalk for a darker circle.',
        'Soul Sand Stock': 'Ritual ground with a texture rituals seem to like.',
        'Netherrack Stock': 'A base layer for rituals that lean toward fire.',
        'Obsidian Stock': 'A dark, stable frame for a ritual circle.',
        'Ender Pearl Stock': 'An offering some spirits are drawn toward.',
        'Diamond Stock': 'A high-value offering for a demanding ritual.',
        'Bound Foliot Book': 'A binding book with a foliot already sealed inside.',
        'Bound Djinni Book': 'A binding book with a djinni already sealed inside.',
        'Bound Afrit Book': 'A binding book with an afrit already sealed inside.',
        'Bound Marid Book': 'A binding book with a marid already sealed inside.',
        'Iesnium Ore': 'A vein sample, worth smelting once you find more.',
        'Miner Afrit Deeps': "An afrit sent deep to mine where lesser spirits won't go.",
    },
    28: {
        'Hand Crank': 'Turn it by hand when nothing else is spinning yet.',
        'Shaft Stock': 'Carries rotation from one machine to the next.',
        'Large Cog': 'Meshes at an angle and shifts rotation speed.',
        'Gearbox': 'Turns rotation around a corner without losing speed.',
        'Gearshift': 'Flips rotation direction with a redstone pulse.',
        'Chain Drive': 'Sends rotation a long way without a wall of shafts.',
        'Adj Chain': 'A chain drive that can reverse or stop on command.',
        'Water Wheel': 'Spins from falling water, slow but steady.',
        'Large Wheel': 'Bigger wheel, more torque from the same current.',
        'Windmill Bearing': 'Turns sails into rotation, pad wind included.',
        'Mechanical Bearing': 'Rotates whole structures built onto it.',
        'Clockwork Bearing': 'Rotates a structure on a schedule, like a clock hand.',
        'Steam Engine': 'Converts boiler steam into steady rotation.',
        'Steam Whistle': 'Blows off pressure with a sound you can hear across the pad.',
        'Blaze Burner': 'Heats basins hot enough for blasting and brewing.',
        'Basin': 'Catches whatever drops into it for mixing or pressing.',
        'Crushing Wheel': 'Two wheels turning against each other, ore fed between them.',
        'Whisk': 'Stirs a basin from above, no hands required.',
        'Propeller': 'Blows items and mobs when spun fast enough.',
        'Depot': 'Holds a single item so machinery can work on it.',
        'Belt': 'Moves items along at whatever speed the shaft gives it.',
        'Andesite Funnel': 'Loads or unloads a belt, one way at a time.',
        'Brass Funnel': 'Filters what it moves, by item and by count.',
        'Chute Line': 'Drops items straight down between floors.',
        'Smart Chute': 'Filters what falls through it.',
        'Fluid Pipe': 'Carries liquid wherever the pump pushes it.',
        'Smart Fluid Pipe': 'Filters which fluid gets through.',
        'Mechanical Pump': 'Pushes fluid through pipes in one direction.',
        'Spout': 'Fills items and containers from above with fluid.',
        'Item Drain': 'Empties fluid out of filled containers.',
        'Fluid Tank': 'Stores a big volume of liquid in one block.',
        'Item Vault': 'A large chest for a pad that outgrew barrels.',
        'Portable Storage': "Loads and unloads a train's inventory at a station.",
        'Portable Fluid': "Loads and unloads a train's fluid tank at a station.",
        'Precision Mech': 'The brass heart of most advanced Create machines.',
        'Electron Tube': 'Lights up brighter the faster it spins.',
        'Brass Hand': "Placed on a shaft, it becomes a deployer's hand.",
        'Mechanical Arm': 'Picks items from one spot and places them in another.',
        'Speed Controller': 'Sets an exact rotation speed for whatever follows it.',
        'Sequenced Gearshift': 'Runs a short program of rotation steps.',
        'Redstone Link': 'Sends a redstone signal without a wire between pads.',
        'Stockpile Switch': 'Signals redstone when an inventory crosses a threshold.',
        'Content Observer': 'Watches an inventory and signals when contents match.',
        'Nixie Tube': 'Displays a number for anyone reading the panel.',
        'Display Board': 'Shows text pulled from a sign or a stock ticker.',
        'Factory Gauge': 'Shows the count of a tracked resource at a glance.',
        'Repackager': 'Turns a stack back into a labeled storage drawer.',
        'Stock Ticker': 'Requests items from storage with a lever pull.',
        'Track': 'Lay it down and a cart has somewhere to go.',
        'Track Station': 'Marks where a train loads, unloads, or waits.',
        'Schedule': 'Tells a train which stations to visit and when.',
        'Cart Assembler': 'Builds a train car onto the track beneath it.',
        'Controller Rail': 'A powered rail with finer speed control.',
        'Elevator Pulley': 'Lifts a whole platform between marked floors.',
        'Gantry Shaft': 'Carries a gantry carriage along its length.',
        'Gantry Carriage': 'Rides a gantry shaft, dragging structure along with it.',
    },
    29: {
        'Certus Crystal': "Grows in caves and holds a network's memory.",
        'Charged Certus': 'A charged crystal, ready for processors and cells.',
        'Fluix Crystal': "Grows fast in water, the digital loom's main crystal.",
        'Fluix Dust': 'Ground fluix, used in glass and cable recipes.',
        'Silicon': "Smelted from certus quartz for the loom's chips.",
        'Sky Stone': 'Meteor stone, the base of every digital loom build.',
        'Smooth Sky Stone': "Smoothed sky stone, used for the controller's shell.",
        'Charger': 'Charges certus crystals under a slow spinning glow.',
        'Printed Calc': 'A printed circuit, pressed before it becomes a processor.',
        'Printed Logic': 'A printed circuit for a logic processor.',
        'Printed Eng': 'A printed circuit for an engineering processor.',
        'Calc Processor': 'A finished chip the loom needs for crafting logic.',
        'Logic Processor': 'A finished chip for storage cells and terminals.',
        'Eng Processor': 'A finished chip for interfaces and buses.',
        'Fluix Glass Cable': "Watch the digital loom's pulse run through clear glass.",
        'Fluix Covered': 'Insulated cable, several channels hidden under one color.',
        'Fluix Smart': 'Cable that can carry and filter its own channels.',
        'Energy Acceptor': 'Feeds outside power into the digital loom.',
        'Dense Energy': 'Stores a deep reserve of power for the network.',
        'Controller': "The loom's spine; every channel radiates out from here.",
        'Drive': 'Holds storage cells and reads them for the network.',
        '1k Component': 'A small storage housing, sealed inside a cell casing.',
        '4k Component': 'A bigger storage housing for a denser cell.',
        '16k Component': 'A mid-sized storage housing, well past the basic size.',
        '64k Component': 'A large storage housing for a serious cell.',
        '256k Component': 'The biggest storage housing short of the archive itself.',
        '1k Item Cell': "Stores items on the network, roughly a chest's worth.",
        '4k Item Cell': 'Stores several chests worth of items on the network.',
        '16k Item Cell': 'Stores a lot of items without touching a barrel.',
        '64k Item Cell': 'Stores a warehouse of items on one small disk.',
        '1k Fluid Cell': 'Stores fluid on the network instead of a tank.',
        'Interface': 'Links the network to a machine or a world block.',
        'Export Bus': 'Pushes items out of the network into a container.',
        'Storage Bus': 'Lets the network read an outside inventory as its own.',
        'Terminal': 'Browse and pull anything the network is holding.',
        'Crafting Terminal': 'Craft directly from whatever the network is storing.',
        'Pattern Encode': 'Writes the recipe a pattern will follow.',
        'Pattern Access': 'Shows every pattern the network currently knows.',
        'Pattern Provider': 'Supplies patterns to machines that craft automatically.',
        'Molecular Assembler': 'Assembles crafted items by following a stored pattern.',
        'Crafting Unit': 'A block of memory the network uses while crafting.',
        'Crafting Accel': 'Speeds up one crafting job running through the network.',
        '1k Craft Storage': 'Adds crafting memory to a crafting unit.',
        '4k Craft Storage': 'More crafting memory for bigger jobs.',
        '16k Craft Storage': 'A serious block of crafting memory.',
        '64k Craft Storage': "Enough crafting memory for the network's biggest jobs.",
        '256k Craft Storage': 'Archive-grade crafting memory, rarely needed but there when it is.',
        'Level Emitter': 'Signals redstone once a tracked item crosses a count.',
        'Formation Plane': 'Places blocks from the network into the world.',
        'Annihilation Plane': 'Breaks blocks and pulls the drops into the network.',
        'P2P Tunnel': 'Carries one network channel across a break in the cable run.',
        'Spatial 2': 'Folds a small chunk of space into a portable cell.',
        'Wireless Terminal': "Browse the network's storage from anywhere with a booster nearby.",
        'Wireless Craft': 'Craft from the network without walking back to a terminal.',
        'Matter Cannon': 'Fires matter balls; charge it before you need it.',
        'Quartz Glass': 'A clear block for controller shells and cable runs.',
        'Quartz Vibrant': 'Glass that glows on its own, no torch required.',
        'Fluix Block': 'A solid storage block, nine crystals condensed into one.',
        'Cell Workbench': 'Partitions a storage cell into several smaller pools.',
    },
    30: {
        'Porcelain Clay': 'Fired clay, a step toward porcelain tools.',
        'Porcelain Bucket': 'A lighter bucket, easier on an early grit budget.',
        'Porcelain Crucible': 'Melts blocks down into liquid over a fire.',
        'String Mesh': 'The first sieve mesh; slow but it works.',
        'Flint Mesh': 'Sieves faster than string, worth the upgrade.',
        'Iron Mesh': 'A solid middle mesh for steady sieving.',
        'Golden Mesh': 'Turns up rarer drops than iron will.',
        'Diamond Mesh': 'Sieves fast enough to keep a hopper line fed.',
        'Netherite Mesh': 'The best mesh a sieve will ever hold.',
        'Void Yarn Stock': "Spun from Strand thread, the pack's own currency fiber.",
        'Binding Knot Stock': 'Knots that hold a path open between distant pads.',
        'Thread Mesh String': 'A void-loom take on the basic sieve mesh.',
        'Thread Mesh Flint': 'A void-loom mesh, a step above plain string.',
        'Thread Mesh Iron': 'A void-loom mesh built for steady output.',
        'Spindle Hammer': 'Crushes compressed blocks back down to dust.',
        'Spindle Crook': 'Pulls thread and knots without breaking stride.',
        'Loomframe': 'Marks a void-loom crafting station.',
        'Tension Barrel': "Holds strain so a sieve line doesn't snap under load.",
        'Compressed Dirt': 'Nine blocks of dirt folded into one for the trip up.',
        'Compressed Cobble': 'Nine cobblestone packed tight, cheap and endless.',
        'Compressed Gravel': 'Nine gravel compacted for storage, not for sieving.',
        'Compressed Sand': 'Nine sand blocks pressed into one for hauling.',
        'Compressed Dust': 'Nine dust blocks pressed down for the same reason.',
        'Compressed Netherrack': 'Nether stone compacted for a lighter inventory.',
        'Compressed End Stone': 'End stone compacted, useful once the void needs feeding.',
        'Compressed Deepslate': 'Deepslate compacted nine to one, still just stone.',
        'Compressed Hammer': 'Smashes a whole stack of compressed blocks apart at once.',
        'Compressed Iron Hammer': 'A weaker hammer for breaking compressed blocks.',
        'Compressed Sieve': 'A wide sieve, several gravel piles at a time.',
        'Birch Sieve': 'Sieves the same as oak, just a different grain.',
        'Birch Barrel': 'Ferments the same as any other barrel.',
        'Birch Crucible': 'Melts blocks the same as any other crucible.',
        'Frayed Thread Stock': "The Strand's currency; earn it, spend it, never waste it.",
        'Whisker Codex': "Assigns quests and tracks a Clowder's progress.",
    },
    31: {
        'Packaged Guide': 'Explains how packages move through the line.',
        'Package Component': "The paper inside a package, before it's sealed shut.",
        'ME Package Comp': 'A package wrapper built around a stored pattern instead.',
        'Packager': 'Seals items into a package for the line to move.',
        'Packager AE': "Packages items straight out of the digital loom's storage.",
        'Packager Ext': 'Adds another packaging slot to a packager.',
        'Unpackager': 'Opens a package back into loose items.',
        'Unpackager AE': 'Opens a package straight back into the digital loom.',
        'Encoder': 'Writes a crafting recipe onto a package pattern.',
        'Crafter': 'Assembles a package by following its encoded recipe.',
        'Crafter AE': "Assembles a package using the digital loom's stored patterns.",
        'Distributor': 'Routes packages toward whichever address matches.',
        'Distributor Marker': 'Marks a destination a distributor can route packages to.',
        'Packaging Provider': 'Feeds finished packages into the line for pickup.',
        'Crafting Proxy': 'Lets a distant crafter request through this block instead.',
        'Recipe Holder': 'Stores a batch of package recipes for reuse.',
        'Settings Cloner': "Copies one block's settings onto another, saves a lot of clicking.",
        'Fluid Package Filler': 'Fills a package with fluid instead of items.',
        'Package Item': 'A sealed bundle of items, ready to move or store.',
        'Volume Package': 'Packs far more into one package than the basic kind.',
        'Proxy Marker': 'Marks where a crafting proxy should reach.',
        'AE Interface': 'Links the packaging line to the digital loom.',
        'Pattern Provider': 'Supplies crafting patterns to the packaging line.',
        'Molecular Assembler': "Crafts items for the digital loom's own patterns.",
        'ME Controller': 'A digital loom network first, or none of this packaging runs.',
        'Create Packager': 'Packs Create-side items the mechanical way.',
        'Create Repackager': 'Turns packages back into a labeled drawer.',
        'Stock Ticker': 'Requests packaged items with a lever pull.',
        'Item Vault': 'A bulk buffer chest for packages waiting their turn.',
    },
    32: {
        'QIO Drive Base': 'A basic quantum storage disk for the QIO network.',
        'QIO Hyper Dense': 'Packs far more storage onto one quantum disk.',
        'QIO Time Dilating': 'A quantum disk that trades size for raw density.',
        'QIO Supermassive': 'The largest quantum disk Mekanism makes.',
        'QIO Drive Array': 'Holds several quantum disks in one housing.',
        'QIO Dashboard': 'Browse everything the QIO network is storing.',
        'Portable QIO': 'Carries the QIO dashboard in your pocket.',
        'Steel Casing': 'The basic shell for most advanced Mekanism machines.',
        'Ultimate Cube': 'Stores an enormous amount of power in one block.',
        'Ultimate Bin': 'Holds a huge stack of one single item.',
        'Ult Smelt Factory': 'Smelts several stacks at once, as fast as Mekanism gets.',
        'Ult Enrich Factory': 'Enriches ore at the fastest speed Mekanism offers.',
        'Ult Crush Factory': 'Crushes ore at the fastest speed Mekanism offers.',
        'Digital Miner': 'Mines out a chunk automatically, straight into the void.',
        'Atomic Disassembler': 'A modular tool that swaps its own working head.',
        'Configurator': 'Rotates faces and copies settings between Mekanism machines.',
        'Teleporter': 'Jumps you instantly between two linked pads.',
        'Teleporter Frame': 'Frames the portal a teleporter opens.',
        'SPS Casing': 'Shell for the reactor that produces antimatter.',
        'SPS Port': 'Feeds chemicals in and pulls antimatter out of the reactor.',
        'Supercharged Coil': "Speeds up an antimatter reactor's output.",
        'Isotopic Centrifuge': 'Spins isotopes apart for late-game chemistry.',
        'Chem Dissolution': 'Dissolves ore into a chemical slurry.',
        'Chem Washer': "Washes slurry clean before it's crystallized.",
        'Chem Crystallizer': 'Turns a chemical back into a solid crystal.',
        'Solar Neutron': 'Bombards material with sunlight-driven neutrons.',
        'Resistive Heater': 'Turns power directly into heat for a boiler.',
        'Fuelwood Heater': 'Burns wood for heat instead of power.',
        'Antiprotonic': 'Late-game synthesis of otherwise impossible materials.',
        'Meka Tool': 'One modular tool for mining, digging, and more.',
        'Meka Helmet': 'Suit armor for the head, upgraded module by module.',
        'Meka Body': 'Suit armor for the chest, upgraded module by module.',
        'Meka Pants': 'Suit armor for the legs, upgraded module by module.',
        'Meka Boots': 'Suit armor for the feet, upgraded module by module.',
        'Boiler Casing': 'Shell for a steam boiler.',
        'Elite Energy Cube': 'Stores a large amount of power.',
        'Adv Energy Cube': 'Stores a moderate amount of power.',
        'Basic Energy Cube': 'Stores a small amount of power, good for starting out.',
        'Metallurgic Infuser': 'Infuses metal with a chemical for new alloys.',
        'Enrichment Chamber': "Doubles the output of raw ore before it's smelted.",
        'Energized Smelter': 'Smelts faster than a furnace, on power instead of fuel.',
        'Precision Sawmill': "Cuts wood with Mekanism's own precision blade.",
        'Electrolytic Sep': 'Splits water into its two component gases.',
        'Chemical Infuser': 'Combines two chemicals into a new one.',
        'Chem Injection': 'Injects a chemical into ore for extra yield.',
        'Osmium Compressor': 'Compresses osmium onto items for tougher gear.',
        'Combiner': 'Combines several components into one finished piece.',
    },
    33: {
        'Rotten Flesh Stock': 'Zombies drop it whether you want it or not.',
        'Bone Stock': 'Skeletons leave these behind; grind them for meal later.',
        'Gunpowder Stock': 'Creepers pay this out, sometimes explosively.',
        'String Stock': 'Spiders drop it, and a sieve never will.',
        'Spider Eye Stock': 'Brews poison and feeds a few odd recipes.',
        'Ender Pearl Farm': 'Endermen drop these; a farm beats begging the void for them.',
        'Blaze Rod Farm': 'Fuel for brewing stands and blaze burners alike.',
        'Ghast Tear Farm': 'A rare drop, key for regeneration potions.',
        'Magma Cream Farm': 'Brews fire resistance and feeds a few crafts.',
        'Slimeball Farm': 'Sticky enough for pistons, slime blocks, and leads.',
        'Wither Skull': 'Three of these summon a boss worth fighting for.',
        'Nether Star': "The wither's own tax, rare and heavy with power.",
        'Shulker Shell Farm': 'Crafts a shulker box, storage that survives death.',
        'Phantom Membrane': 'Repairs elytra when nothing else will.',
        'Ink Sac Farm': 'Squid ink, useful for dye and old-fashioned writing.',
        'Glow Ink': 'Makes signs and item frames glow in the dark.',
        'Prismarine Shard': 'Guardians drop it for prismarine blocks and lanterns.',
        'Prismarine Crystal': 'Guardian drop that lights the sea and fuels a few crafts.',
        'Heart of the Sea': 'The core of a conduit, one per build.',
        'Nautilus Shell': 'Rings a conduit; gather eight to finish the frame.',
        'Totem': "Cheats death once, then it's gone.",
        'Iron Golem Gift': 'Golems shed iron while they stand guard.',
        'Snow Golem': 'Throws snowballs; useful ammunition, not much of a fighter.',
        'Arrow Farm': 'Skeletons keep the pad stocked with ammunition.',
        'Spectral Arrow': 'Marks whatever it hits with a temporary glow.',
        'Name Tag Farm': 'Names a mob so it never despawns.',
        'Egg Stock': 'Chickens lay them faster than you can collect.',
        'Wool Stock': 'Sheep grow it back after a trim.',
        'Pork Stock': 'Pigs provide it, cook it before eating.',
        'Mutton Stock': 'Sheep meat, better roasted than raw.',
        'Rabbit Hide': 'A handful makes leather, given enough patience.',
        'Rabbit Foot': 'Brews a potion of luck, if you can spare one.',
        'Zombie Head': 'A showpiece worth setting beside a dragon egg.',
        'Skeleton Skull': 'Pairs nicely with a dragon egg on a shelf.',
        'Creeper Head': 'Another head for the trophy shelf by the egg.',
        'Piglin Head': 'One more head, at home near a dragon egg.',
        'Dragon Head': 'The rarest head, earned only after the fight is over.',
        'Player Head': 'Only if a player happens to drop one.',
    },
    34: {
        'Manifested Ingot': 'Metal willed into being by Spirit Pulse instead of a furnace.',
        'Blank Seal': 'An unwritten seal, waiting for a rite to fill it.',
        'March Stone': "Stone from the March, underfoot in a place that shouldn't exist.",
        'March Cobble': 'Rubble from the March, plain but plentiful.',
        'March Log': "Wood grown somewhere the sun doesn't reach.",
        'March Planks': 'Sawn timber from the March, sturdy despite where it came from.',
        'March Leaf': 'Leaves that murmur even without any wind.',
        'Spirit Reed': 'A reed that hums with leftover Spirit Pulse.',
    },
}
